# Generated by Django 5.0.3 on 2024-04-14 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=50, null=True)),
                ('nombre', models.CharField(max_length=50, null=True)),
                ('apellido', models.CharField(max_length=50, null=True)),
                ('email', models.CharField(max_length=50, null=True)),
                ('fecha_nacimiento', models.DateField()),
                ('situacion_laboral', models.CharField(max_length=50, null=True)),
                ('numero_hijos', models.IntegerField()),
                ('nivel_educativo', models.CharField(max_length=50, null=True)),
                ('afp', models.CharField(max_length=50, null=True)),
                ('seguro_medico', models.CharField(max_length=50, null=True)),
                ('persona_confianza', models.CharField(max_length=50, null=True)),
                ('casos_judicializados', models.CharField(max_length=50, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('abreviacion', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Informe_indicadores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('abreviacion', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Institucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, null=True)),
                ('tipo_origen', models.CharField(max_length=50, null=True)),
                ('descripcion', models.TextField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('comuna', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.comuna')),
            ],
        ),
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, null=True)),
                ('descripcion', models.TextField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('comuna', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.comuna')),
                ('institucion_origen', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.institucion')),
            ],
        ),
        migrations.CreateModel(
            name='Profesional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=50, null=True)),
                ('nombre', models.CharField(max_length=50, null=True)),
                ('apellido', models.CharField(max_length=50, null=True)),
                ('email', models.CharField(max_length=50, null=True)),
                ('profesion', models.CharField(max_length=50, null=True)),
                ('cargo_laboral', models.CharField(max_length=50, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('programa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.programa')),
            ],
        ),
        migrations.CreateModel(
            name='Planilla_Derivacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('casos_judicializados', models.TextField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('beneficiaria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.beneficiaria')),
                ('comuna', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.comuna')),
                ('profesional_derivante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.profesional')),
                ('programa_destino', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.programa')),
            ],
            options={
                'ordering': ['-updated', '-created'],
            },
        ),
        migrations.AddField(
            model_name='comuna',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.region'),
        ),
        migrations.CreateModel(
            name='Registro_Intervencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_intervencion', models.TextField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('beneficiaria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.beneficiaria')),
                ('comuna', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.comuna')),
                ('profesional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.profesional')),
                ('programa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.programa')),
            ],
            options={
                'ordering': ['-updated', '-created'],
            },
        ),
    ]
