# Generated by Django 5.0.3 on 2024-04-25 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_host_comunidad_administrador_user_apellido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiaria',
            name='rut',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
