# Generated by Django 5.0.3 on 2024-04-22 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_pais_alter_comuna_nombre_alter_region_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='pais',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.pais'),
        ),
    ]
