# Generated by Django 5.0.3 on 2024-04-22 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_region_pais'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='region',
            name='abreviacion',
        ),
    ]
