# Generated by Django 5.0.3 on 2024-05-03 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_planilla_derivacion_documento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiaria',
            name='telefono',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='planilla_derivacion',
            name='contacto_beneficiaria',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
