# Generated by Django 5.0.3 on 2024-04-22 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_remove_region_abreviacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='region',
            name='pais',
        ),
        migrations.DeleteModel(
            name='Pais',
        ),
    ]
