# Generated by Django 5.0.3 on 2024-04-22 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_remove_region_pais_delete_pais'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comuna',
            name='abreviacion',
        ),
        migrations.AddField(
            model_name='region',
            name='numero',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.region')),
            ],
        ),
        migrations.AddField(
            model_name='comuna',
            name='provincia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.provincia'),
        ),
    ]
